### ISSUE TITLE
You could make a tutorial?

### ISSUE THREAD

**Issue by mrcanelas** [adrianojn/translatedb#1]
Hey man, I could do a tutorial on how do I translate cards.cdb? I tried to do the same for min but not censegui, I want to translate to Portuguese, has as?

**Comment by adrianojn** [comment]
Esse repositório está desatualizado, use https://github.com/adrianojn/wikia

Tutorial em protuguês:

---
1. Crie uma pasta para colocar os arquivos.
   Os comandos precisam ser execultados de dentro dessa pasta.
2. Coloque os arquivos `config.json` e `cards.cdb` (versão em Inglês) dentro da pasta
3. Copie `cards.cdb` para `cards-pt.cdb`
4. Execulte o comando `wikia -update -lang pt`
5. Execulte o comando `wikia -translate -lang pt`

**Comment by mrcanelas** [comment]
Ok cara obrigado, vou tentar.
